---
title: "ifo Business Climate Index"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ifo Publication}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### ifo Business Climate Germany

```{r climate, message = FALSE, dpi = 300}
library(dplyr)
library(ggplot2)
library(ifo)

climate <- ifo_climate()

climate |>
  select(yearmonth, ends_with("index")) |>
  tidyr::pivot_longer(-yearmonth, names_to = "component") |>
  mutate(component = sub("_index", "", component, fixed = TRUE)) |>
  ggplot(aes(x = yearmonth, y = value, color = component)) +
  geom_line() +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    legend.position = "top",
    plot.caption = element_text(
      hjust = 0, vjust = 0, size = 10, margin = margin(10, 0, 0, 0)
    ),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  labs(
    title = "ifo Business Climate Germany", subtitle = "Seasonally adjusted",
    y = NULL, x = NULL,
    caption = sprintf(
      "Source: ifo Business Survey, %s.", format(max(climate$yearmonth), "%B %Y")
    )
  ) +
  scale_color_manual(
    values = c(climate = "darkred", situation = "darkgrey", expectation = "darkblue"),
    labels = c(
      "ifo Business Climate",
      "Assessment of business situtation",
      "Business expectation"
    )
  )
```

### ifo Business Climate by Sector

```{r sector, dpi = 300}
sectors <- ifo_climate("sectors")

sectors |>
  select(yearmonth, ends_with("balance")) |>
  tidyr::pivot_longer(-yearmonth,
    names_to = c("component", "sector"), names_pattern = "(.*)_(.*)_balance"
  ) |>
  filter(
    sector %in% c("manufacturing", "services", "trade", "construction"),
    yearmonth >= "2020-01-01"
  ) |>
  mutate(
    sector = factor(sector,
      levels = c("manufacturing", "services", "trade", "construction")
    )
  ) |>
  ggplot(aes(x = yearmonth, y = value, color = component)) +
  geom_line() +
  facet_wrap(~sector,
    labeller = labeller(sector = c(
      manufacturing = "Manufacturing",
      services = "Service Sector",
      trade = "Trade",
      construction = "Construction"
    ))
  ) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    legend.position = "top",
    plot.caption = element_text(
      hjust = 0, vjust = 0, size = 10, margin = margin(10, 0, 0, 0)
    ),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  labs(
    title = "ifo Business Climate, Business Situation, and Expectations by Sector",
    subtitle = "Balances, seasonally adjusted",
    y = NULL, x = NULL,
    caption = sprintf(
      "Source: ifo Business Survey, %s.", format(max(sectors$yearmonth), "%B %Y")
    )
  ) +
  scale_color_manual(
    values = c(climate = "darkred", situation = "darkgrey", expectation = "darkblue"),
    labels = c(
      "ifo Business Climate",
      "Assessment of business situtation",
      "Business expectation"
    )
  )
```
